# Part 1: Data Extraction, Cleaning & Database
**Source:** https://en.wikipedia.org/wiki/List_of_highest-grossing_films

**Pipeline:**
1. Fetch main table → rank, title, box_office, year
2. Fetch each film's infobox → director, country
3. Clean all columns
4. Save to SQLite
5. Export to JSON for GitHub Pages

## 0. Imports

In [ ]:
# !pip install requests beautifulsoup4 lxml pandas

import requests
from bs4 import BeautifulSoup
import pandas as pd
import sqlite3
import time
import re
import os
import json

HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
}
BASE    = 'https://en.wikipedia.org'
print('OK')

OK

## 1. Fetch Main Table

In [76]:
URL  = 'https://en.wikipedia.org/wiki/List_of_highest-grossing_films'
resp = requests.get(URL, headers=HEADERS, timeout=15)
assert resp.status_code == 200

soup  = BeautifulSoup(resp.text, 'lxml')
table = soup.find('table', class_='wikitable')

cols = [th.get_text(strip=True) for th in table.find('tr').find_all(['th','td'])]

In [77]:
# Adjust if column order differs from what's printed above
COL_RANK, COL_TITLE, COL_BOX_OFFICE, COL_YEAR = 0, 2, 3, 4

def cell_text(cells, idx):
    if idx >= len(cells): return None
    t = cells[idx].get_text(separator=' ', strip=True)
    return re.sub(r'\[[^\]]*\]', '', t).strip() or None

rows_data = []
for row in table.find_all('tr')[1:]:
    cells = row.find_all(['td','th'])
    if len(cells) < 4: continue
    wiki_url = wiki_slug = None
    if COL_TITLE < len(cells):
        for a in cells[COL_TITLE].find_all('a', href=True):
            if a['href'].startswith('/wiki/'):
                wiki_url  = BASE + a['href']
                wiki_slug = a['href'].replace('/wiki/', '')
                break

    rows_data.append({
        'rank':       cell_text(cells, COL_RANK),
        'title':      cell_text(cells, COL_TITLE),
        'box_office': cell_text(cells, COL_BOX_OFFICE),
        'year':       cell_text(cells, COL_YEAR),
        'wiki_url':   wiki_url,
        'wiki_slug':  wiki_slug,
    })

df = pd.DataFrame(rows_data)
print(f'Rows: {len(df)}')
df.head()

Rows: 50

,rank,title,box_office,year,wiki_url,wiki_slug
0,1,Avatar,"$2,923,710,708",2009,https://en.wikipedia.org/wiki/Avatar_(2009_film),Avatar_(2009_film)
1,2,Avengers: Endgame,"$2,797,501,328",2019,https://en.wikipedia.org/wiki/Avengers:_Endgame,Avengers:_Endgame
2,3,Avatar: The Way of Water,"$2,334,484,620",2022,https://en.wikipedia.org/wiki/Avatar:_The_Way_...,Avatar:_The_Way_of_Water
3,4,Titanic,"T $2,257,906,828",1997,https://en.wikipedia.org/wiki/Titanic_(1997_film),Titanic_(1997_film)
4,5,Ne Zha 2,"NZ $2,215,690,000",2025,https://en.wikipedia.org/wiki/Ne_Zha_2,Ne_Zha_2

## 2. Scrape Director & Country from Each Film's Infobox

Wikipedia infoboxes have varying structure. The `get_infobox_field` function
tries three strategies in order of reliability:

| Priority | Strategy | Why |
|---|---|---|
| 1 | `<a>` link texts (skip `#` anchors) | Most films — director has a Wikipedia article |
| 2 | `<li>` item texts | Some films list directors in `<ul><li>` without links |
| 3 | Raw `.get_text()` | Fallback for plain text cells |

In [ ]:
import re
import requests
import time
from bs4 import BeautifulSoup

# Обязательно представляемся браузером, чтобы избежать 403 ошибок
HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
}

def get_infobox_field(td):
    """Очищает текст ячейки от мусора и склеивания."""
    for tag in td.find_all(['sup', 'style']):
        tag.decompose()
    for span in td.find_all('span', style=lambda v: v and 'display:none' in v.replace(' ', '')):
        span.decompose()

    for br in td.find_all(['br', 'hr']):
        br.replace_with('\n')
    for li in td.find_all('li'):
        li.insert_after('\n')

    raw_text = td.get_text(separator='\n', strip=True)
    
    seen = set()
    out = []
    for line in raw_text.split('\n'):
        line = re.sub(r'\[[^\]]*\]', '', line)  
        line = line.replace('\xa0', ' ').replace('\u200b', '').strip()
        line = re.sub(r'\s+', ' ', line)
        
        if line and line not in seen:
            seen.add(line)
            out.append(line)

    # Если ничего не нашли, возвращаем строку "Unknown" вместо None
    return ', '.join(out) if out else "Unknown"


def scrape_infobox(url):
    """Ищет режиссера и страну, отсекая любые None."""
    # Если URL пустой, сразу отдаем заглушки
    if not url or str(url).lower() == 'nan':
        return "Unknown", "Unknown"
        
    try:
        r = requests.get(url, headers=HEADERS, timeout=10)
        if r.status_code != 200:
            print(f"[{r.status_code}] Ошибка доступа к {url}")
            return "Unknown", "Unknown"
            
        page = BeautifulSoup(r.text, 'lxml')
        
        # Ищем ЛЮБЫЕ таблицы, в классе которых есть слово infobox (игнорируя регистр)
        infoboxes = page.find_all('table', class_=re.compile(r'infobox', re.I))
        
        director = "Unknown"
        country = "Unknown"
        
        for infobox in infoboxes:
            for tr in infobox.find_all('tr'):
                # Ищем любые заголовки
                th = tr.find(['th', 'td'], class_=re.compile(r'infobox-label', re.I)) or tr.find('th')
                td = tr.find('td', class_=re.compile(r'infobox-data', re.I)) or tr.find('td')
                
                if not th or not td:
                    continue
                
                label = th.get_text(separator=' ', strip=True).lower().replace('\xa0', ' ')
                
                # Ловим direct, directed, director, directors, filmmaker
                if ('direct' in label or 'filmmaker' in label) and director == "Unknown":
                    director = get_infobox_field(td)
                    
                # Ловим country, countries, origin, nationality
                if ('countr' in label or 'origin' in label or 'nation' in label) and country == "Unknown":
                    country = get_infobox_field(td)
            
            # Если оба поля заполнены (не Unknown), прекращаем поиск
            if director != "Unknown" and country != "Unknown":
                break
                
        return director, country
    except Exception as e:
        print(f'{url}: {e}')
        return "Unknown", "Unknown"

In [88]:
# Создаем пустые списки для новых колонок
directors = []
countries = []

print("Начинаем сбор...")
for i, row in df.iterrows():
    d, c = scrape_infobox(row['wiki_url'])
    directors.append(d)
    countries.append(c)
    
    # Печатаем прогресс
    print(f"[{i+1}/{len(df)}] {row['title']} ... dir={d!r}  country={c!r}")
    
    # Спим 1 секунду между запросами, чтобы не бесить Википедию
    time.sleep(1)

# Записываем результаты обратно в датафрейм
df['director'] = directors
df['country'] = countries

Начинаем сбор...
[1/50] Avatar ... dir='James Cameron'  country='United States, United Kingdom'
[2/50] Avengers: Endgame ... dir='Anthony Russo, Joe Russo'  country='United States'
[3/50] Avatar: The Way of Water ... dir='James Cameron'  country='United States'
[4/50] Titanic ... dir='James Cameron'  country='United States'
[5/50] Ne Zha 2 ... dir='Jiaozi'  country='China'
[6/50] Star Wars: The Force Awakens ... dir='J. J. Abrams'  country='United States'
[7/50] Avengers: Infinity War ... dir='Anthony Russo, Joe Russo'  country='United States'
[8/50] Spider-Man: No Way Home ... dir='Jon Watts'  country='United States'
[9/50] Zootopia 2 † ... dir='Jared Bush, Byron Howard'  country='United States'
[10/50] Inside Out 2 ... dir='Kelsey Mann'  country='United States'
[11/50] Jurassic World ... dir='Colin Trevorrow'  country='United States'
[12/50] The Lion King ... dir='Jon Favreau'  country='United States'
[13/50] The Avengers ... dir='Joss Whedon'  country='United States'
[14/50] Furious 7 ... dir='James Wan'  country='United States'
[15/50] Top Gun: Maverick ... dir='Joseph Kosinski'  country='United States'
[16/50] Avatar: Fire and Ash † ... dir='James Cameron'  country='United States'
[17/50] Frozen 2 ... dir='Chris Buck, Jennifer Lee'  country='United States'
[18/50] Barbie ... dir='Greta Gerwig'  country='United States, United Kingdom'
[19/50] Avengers: Age of Ultron ... dir='Joss Whedon'  country='United States'
[20/50] The Super Mario Bros. Movie ... dir='Aaron Horvath, Michael Jelenic'  country='United States'
[21/50] Black Panther ... dir='Ryan Coogler'  country='United States'
[22/50] Harry Potter and the Deathly Hallows – Part 2 ... dir='David Yates'  country='United Kingdom, United States'
[23/50] Deadpool & Wolverine ... dir='Shawn Levy'  country='United States'
[24/50] Star Wars: The Last Jedi ... dir='Rian Johnson'  country='United States'
[25/50] Jurassic World: Fallen Kingdom ... dir='J. A. Bayona'  country='United States'
[26/50] Frozen ... dir='Chris Buck, Jennifer Lee'  country='United States'
[27/50] Beauty and the Beast ... dir='Bill Condon'  country='United States'
[28/50] Incredibles 2 ... dir='Brad Bird'  country='United States'
[29/50] The Fate of the Furious ... dir='F. Gary Gray'  country='United States'
[30/50] Iron Man 3 ... dir='Shane Black'  country='United States'
[31/50] Minions ... dir='Pierre Coffin, Kyle Balda'  country='United States'
[32/50] Captain America: Civil War ... dir='Anthony Russo, Joe Russo'  country='United States'
[33/50] Aquaman ... dir='James Wan'  country='United States'
[34/50] The Lord of the Rings: The Return of the King ... dir='Peter Jackson'  country='New Zealand, Germany, United States'
[35/50] Spider-Man: Far From Home ... dir='Jon Watts'  country='United States'
[36/50] Captain Marvel ... dir='Anna Boden, Ryan Fleck'  country='United States'
[37/50] Transformers: Dark of the Moon ... dir='Michael Bay'  country='United States'
[38/50] Skyfall ... dir='Sam Mendes'  country='United Kingdom, United States'
[403] Ошибка доступа к https://en.wikipedia.org/wiki/Transformers:_Age_of_Extinction
[39/50] Transformers: Age of Extinction ... dir=None  country=None
[40/50] The Dark Knight Rises ... dir='Christopher Nolan'  country='United States, United Kingdom'
[41/50] Joker ... dir='Todd Phillips'  country='United States'
[42/50] Star Wars: The Rise of Skywalker ... dir='J. J. Abrams'  country='United States'
[43/50] Toy Story 4 ... dir='Josh Cooley'  country='United States'
[44/50] Toy Story 3 ... dir='Lee Unkrich'  country='United States'
[45/50] Pirates of the Caribbean: Dead Man's Chest ... dir='Gore Verbinski'  country='United States'
[46/50] Moana 2 ... dir='David Derrick Jr., Jason Hand, Dana Ledoux Miller'  country='United States'
[403] Ошибка доступа к https://en.wikipedia.org/wiki/Rogue_One:_A_Star_Wars_Story
[47/50] Rogue One: A Star Wars Story ... dir=None  country=None
[48/50] Aladdin ... dir='Guy Ritchie'  country='United States'
[49/50] Star Wars: Episode I – The Phantom Menace ... dir='George Lucas'  country='United States'
[50/50] Pirates of the Caribbean: On Stranger Tides ... dir='Rob Marshall'  country='United States'

## 3. Clean All Columns

In [89]:
df_clean = df.drop(columns=['wiki_url', 'wiki_slug']).copy()

# rank & year → integer
df_clean['rank'] = pd.to_numeric(df_clean['rank'], errors='coerce').astype('Int64')
df_clean['year'] = pd.to_numeric(df_clean['year'], errors='coerce').astype('Int64')

# title: remove dagger † (Wikipedia marks for estimated figures)
df_clean['title'] = df_clean['title'].str.replace(r'\s*†\s*', '', regex=True).str.strip()

# box_office: strip prefix abbreviations like 'T $', 'NZ $', 'F8 $'
# Strategy: find the first '$' and parse digits+commas after it
def parse_box_office(val):
    if pd.isna(val): return None
    m = re.search(r'\$([\d,]+)', str(val))
    return float(m.group(1).replace(',', '')) if m else None

df_clean['box_office'] = df_clean['box_office'].apply(parse_box_office)

# country & director: remove empty comma fragments, deduplicate
def clean_list_field(val):
    if pd.isna(val) or val is None: return None
    parts = [p.strip() for p in str(val).split(',')]
    seen, unique = set(), []
    for p in parts:
        if p and p not in seen:
            seen.add(p)
            unique.append(p)
    return ', '.join(unique) or None

df_clean['country']  = df_clean['country'].apply(clean_list_field)
df_clean['director'] = df_clean['director'].apply(clean_list_field)

df_clean = df_clean[['rank', 'title', 'year', 'director', 'box_office', 'country']]

In [90]:
pd.set_option('display.max_colwidth', 50)
pd.set_option('display.max_rows', 60)
display(df_clean)

,rank,title,year,director,box_office,country
0,1,Avatar,2009,James Cameron,2.923711e+09,"United States, United Kingdom"
1,2,Avengers: Endgame,2019,"Anthony Russo, Joe Russo",2.797501e+09,United States
2,3,Avatar: The Way of Water,2022,James Cameron,2.334485e+09,United States
3,4,Titanic,1997,James Cameron,2.257907e+09,United States
4,5,Ne Zha 2,2025,Jiaozi,2.215690e+09,China
5,6,Star Wars: The Force Awakens,2015,J. J. Abrams,2.068224e+09,United States
6,7,Avengers: Infinity War,2018,"Anthony Russo, Joe Russo",2.048360e+09,United States
7,8,Spider-Man: No Way Home,2021,Jon Watts,1.922599e+09,United States
8,9,Zootopia 2,2025,"Jared Bush, Byron Howard",1.866590e+09,United States
9,10,Inside Out 2,2024,Kelsey Mann,1.698864e+09,United States
10,11,Jurassic World,2015,Colin Trevorrow,1.671537e+09,United States
11,12,The Lion King,2019,Jon Favreau,1.656943e+09,United States
12,13,The Avengers,2012,Joss Whedon,1.518816e+09,United States
13,14,Furious 7,2015,James Wan,1.515341e+09,United States
14,15,Top Gun: Maverick,2022,Joseph Kosinski,1.495696e+09,United States
15,16,Avatar: Fire and Ash,2025,James Cameron,1.485690e+09,United States
16,17,Frozen 2,2019,"Chris Buck, Jennifer Lee",1.450027e+09,United States
17,18,Barbie,2023,Greta Gerwig,1.447138e+09,"United States, United Kingdom"
18,19,Avengers: Age of Ultron,2015,Joss Whedon,1.402810e+09,United States
19,20,The Super Mario Bros. Movie,2023,"Aaron Horvath, Michael Jelenic",1.360880e+09,United States
20,21,Black Panther,2018,Ryan Coogler,1.347281e+09,United States
21,22,Harry Potter and the Deathly Hallows – Part 2,2011,David Yates,1.342140e+09,"United Kingdom, United States"
22,23,Deadpool & Wolverine,2024,Shawn Levy,1.338074e+09,United States
23,24,Star Wars: The Last Jedi,2017,Rian Johnson,1.332540e+09,United States
24,25,Jurassic World: Fallen Kingdom,2018,J. A. Bayona,1.308476e+09,United States
25,26,Frozen,2013,"Chris Buck, Jennifer Lee",1.290000e+09,United States
26,27,Beauty and the Beast,2017,Bill Condon,1.263521e+09,United States
27,28,Incredibles 2,2018,Brad Bird,1.242805e+09,United States
28,29,The Fate of the Furious,2017,F. Gary Gray,1.238765e+09,United States
29,30,Iron Man 3,2013,Shane Black,1.214811e+09,United States
30,31,Minions,2015,"Pierre Coffin, Kyle Balda",1.159445e+09,United States
31,32,Captain America: Civil War,2016,"Anthony Russo, Joe Russo",1.153337e+09,United States
32,33,Aquaman,2018,James Wan,1.148528e+09,United States
33,34,The Lord of the Rings: The Return of the King,2003,Peter Jackson,1.147997e+09,"New Zealand, Germany, United States"
34,35,Spider-Man: Far From Home,2019,Jon Watts,1.132680e+09,United States
35,36,Captain Marvel,2019,"Anna Boden, Ryan Fleck",1.128275e+09,United States
36,37,Transformers: Dark of the Moon,2011,Michael Bay,1.123794e+09,United States
37,38,Skyfall,2012,Sam Mendes,1.108594e+09,"United Kingdom, United States"
38,39,Transformers: Age of Extinction,2014,None,1.104054e+09,None
39,40,The Dark Knight Rises,2012,Christopher Nolan,1.081170e+09,"United States, United Kingdom"
40,41,Joker,2019,Todd Phillips,1.074458e+09,United States
41,42,Star Wars: The Rise of Skywalker,2019,J. J. Abrams,1.074144e+09,United States
42,43,Toy Story 4,2019,Josh Cooley,1.073395e+09,United States
43,44,Toy Story 3,2010,Lee Unkrich,1.066971e+09,United States
44,45,Pirates of the Caribbean: Dead Man's Chest,2006,Gore Verbinski,1.066180e+09,United States
45,46,Moana 2,2024,"David Derrick Jr., Jason Hand, Dana Ledoux Miller",1.059242e+09,United States
46,47,Rogue One: A Star Wars Story,2016,None,1.057420e+09,None
47,48,Aladdin,2019,Guy Ritchie,1.050694e+09,United States
48,49,Star Wars: Episode I – The Phantom Menace,1999,George Lucas,1.046515e+09,United States
49,50,Pirates of the Caribbean: On Stranger Tides,2011,Rob Marshall,1.045714e+09,United States

inserting missing values

In [82]:
df.loc[24, 'director'] = 'J. A. Bayona'
df.loc[24, 'country'] = 'United States'

In [83]:
df.loc[38, 'director'] = 'Michael Bay'
df.loc[38,'country'] = 'United States'

In [84]:
display(df_clean)

,rank,title,year,director,box_office,country
0,1,Avatar,2009,James Cameron,2.923711e+09,"United States, United Kingdom"
1,2,Avengers: Endgame,2019,"Anthony Russo, Joe Russo",2.797501e+09,United States
2,3,Avatar: The Way of Water,2022,James Cameron,2.334485e+09,United States
3,4,Titanic,1997,James Cameron,2.257907e+09,United States
4,5,Ne Zha 2,2025,Jiaozi,2.215690e+09,China
5,6,Star Wars: The Force Awakens,2015,J. J. Abrams,2.068224e+09,United States
6,7,Avengers: Infinity War,2018,"Anthony Russo, Joe Russo",2.048360e+09,United States
7,8,Spider-Man: No Way Home,2021,Jon Watts,1.922599e+09,United States
8,9,Zootopia 2,2025,"Jared Bush, Byron Howard",1.866590e+09,United States
9,10,Inside Out 2,2024,Kelsey Mann,1.698864e+09,United States
10,11,Jurassic World,2015,Colin Trevorrow,1.671537e+09,United States
11,12,The Lion King,2019,Jon Favreau,1.656943e+09,United States
12,13,The Avengers,2012,Joss Whedon,1.518816e+09,United States
13,14,Furious 7,2015,James Wan,1.515341e+09,United States
14,15,Top Gun: Maverick,2022,Joseph Kosinski,1.495696e+09,United States
15,16,Avatar: Fire and Ash,2025,James Cameron,1.485690e+09,United States
16,17,Frozen 2,2019,"Chris Buck, Jennifer Lee",1.450027e+09,United States
17,18,Barbie,2023,Greta Gerwig,1.447138e+09,"United States, United Kingdom"
18,19,Avengers: Age of Ultron,2015,Joss Whedon,1.402810e+09,United States
19,20,The Super Mario Bros. Movie,2023,"Aaron Horvath, Michael Jelenic",1.360880e+09,United States
20,21,Black Panther,2018,Ryan Coogler,1.347281e+09,United States
21,22,Harry Potter and the Deathly Hallows – Part 2,2011,David Yates,1.342140e+09,"United Kingdom, United States"
22,23,Deadpool & Wolverine,2024,Shawn Levy,1.338074e+09,United States
23,24,Star Wars: The Last Jedi,2017,Rian Johnson,1.332540e+09,United States
24,25,Jurassic World: Fallen Kingdom,2018,J. A. Bayona,1.308476e+09,United States
25,26,Frozen,2013,"Chris Buck, Jennifer Lee",1.290000e+09,United States
26,27,Beauty and the Beast,2017,Bill Condon,1.263521e+09,United States
27,28,Incredibles 2,2018,Brad Bird,1.242805e+09,United States
28,29,The Fate of the Furious,2017,F. Gary Gray,1.238765e+09,United States
29,30,Iron Man 3,2013,Shane Black,1.214811e+09,United States
30,31,Minions,2015,"Pierre Coffin, Kyle Balda",1.159445e+09,United States
31,32,Captain America: Civil War,2016,"Anthony Russo, Joe Russo",1.153337e+09,United States
32,33,Aquaman,2018,James Wan,1.148528e+09,United States
33,34,The Lord of the Rings: The Return of the King,2003,Peter Jackson,1.147997e+09,"New Zealand, Germany, United States"
34,35,Spider-Man: Far From Home,2019,Jon Watts,1.132680e+09,United States
35,36,Captain Marvel,2019,"Anna Boden, Ryan Fleck",1.128275e+09,United States
36,37,Transformers: Dark of the Moon,2011,Michael Bay,1.123794e+09,United States
37,38,Skyfall,2012,Sam Mendes,1.108594e+09,"United Kingdom, United States"
38,39,Transformers: Age of Extinction,2014,None,1.104054e+09,None
39,40,The Dark Knight Rises,2012,Christopher Nolan,1.081170e+09,"United States, United Kingdom"
40,41,Joker,2019,Todd Phillips,1.074458e+09,United States
41,42,Star Wars: The Rise of Skywalker,2019,J. J. Abrams,1.074144e+09,United States
42,43,Toy Story 4,2019,Josh Cooley,1.073395e+09,United States
43,44,Toy Story 3,2010,Lee Unkrich,1.066971e+09,United States
44,45,Pirates of the Caribbean: Dead Man's Chest,2006,Gore Verbinski,1.066180e+09,United States
45,46,Moana 2,2024,"David Derrick Jr., Jason Hand, Dana Ledoux Miller",1.059242e+09,United States
46,47,Rogue One: A Star Wars Story,2016,None,1.057420e+09,None
47,48,Aladdin,2019,Guy Ritchie,1.050694e+09,United States
48,49,Star Wars: Episode I – The Phantom Menace,1999,George Lucas,1.046515e+09,United States
49,50,Pirates of the Caribbean: On Stranger Tides,2011,Rob Marshall,1.045714e+09,United States

In [85]:
%pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\79378\anaconda3\lib\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in c:\users\79378\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\79378\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\79378\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [91]:
from sqlalchemy import create_engine

# 1. Connetion
db_user = 'postgres'
db_password = ''
db_host = 'localhost'
db_port = '5432'
db_name = 'films'

connection_string = f'postgresql://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}'
engine = create_engine(connection_string)

# 2.# 2. Download dataframe to PostgreAdmin
try:
    df_clean.to_sql('films', engine, if_exists='append', index=False)
except Exception as e:
    print(f"Erro: {e}")

Erro: (psycopg2.errors.UniqueViolation) ОШИБКА:  повторяющееся значение ключа нарушает ограничение уникальности "films_pkey"
DETAIL:  Ключ "(rank)=(1)" уже существует.

[SQL: INSERT INTO films (rank, title, year, director, box_office, country) VALUES (%(rank__0)s, %(title__0)s, %(year__0)s, %(director__0)s, %(box_office__0)s, %(country__0)s), (%(rank__1)s, %(title__1)s, %(year__1)s, %(director__1)s, %(box_office__1)s, %(c ... 4664 characters truncated ... , (%(rank__49)s, %(title__49)s, %(year__49)s, %(director__49)s, %(box_office__49)s, %(country__49)s)]
[parameters: {'director__0': 'James Cameron', 'rank__0': 1, 'title__0': 'Avatar', 'box_office__0': 2923710708.0, 'country__0': 'United States, United Kingdom', 'year__0': 2009, 'director__1': 'Anthony Russo, Joe Russo', 'rank__1': 2, 'title__1': 'Avengers: Endgame', 'box_office__1': 2797501328.0, 'country__1': 'United States', 'year__1': 2019, 'director__2': 'James Cameron', 'rank__2': 3, 'title__2': 'Avatar: The Way of Water', 'box_office__2': 2334484620.0, 'country__2': 'United States', 'year__2': 2022, 'director__3': 'James Cameron', 'rank__3': 4, 'title__3': 'Titanic', 'box_office__3': 2257906828.0, 'country__3': 'United States', 'year__3': 1997, 'director__4': 'Jiaozi', 'rank__4': 5, 'title__4': 'Ne Zha 2', 'box_office__4': 2215690000.0, 'country__4': 'China', 'year__4': 2025, 'director__5': 'J. J. Abrams', 'rank__5': 6, 'title__5': 'Star Wars: The Force Awakens', 'box_office__5': 2068223624.0, 'country__5': 'United States', 'year__5': 2015, 'director__6': 'Anthony Russo, Joe Russo', 'rank__6': 7, 'title__6': 'Avengers: Infinity War', 'box_office__6': 2048359754.0, 'country__6': 'United States', 'year__6': 2018, 'director__7': 'Jon Watts', 'rank__7': 8, 'title__7': 'Spider-Man: No Way Home', 'box_office__7': 1922598800.0, 'country__7': 'United States', 'year__7': 2021, 'director__8': 'Jared Bush, Byron Howard', 'rank__8': 9 ... 200 parameters truncated ... 'country__41': 'United States', 'year__41': 2019, 'director__42': 'Josh Cooley', 'rank__42': 43, 'title__42': 'Toy Story 4', 'box_office__42': 1073394593.0, 'country__42': 'United States', 'year__42': 2019, 'director__43': 'Lee Unkrich', 'rank__43': 44, 'title__43': 'Toy Story 3', 'box_office__43': 1066970811.0, 'country__43': 'United States', 'year__43': 2010, 'director__44': 'Gore Verbinski', 'rank__44': 45, 'title__44': "Pirates of the Caribbean: Dead Man's Chest", 'box_office__44': 1066179747.0, 'country__44': 'United States', 'year__44': 2006, 'director__45': 'David Derrick Jr., Jason Hand, Dana Ledoux Miller', 'rank__45': 46, 'title__45': 'Moana 2', 'box_office__45': 1059242164.0, 'country__45': 'United States', 'year__45': 2024, 'director__46': None, 'rank__46': 47, 'title__46': 'Rogue One: A Star Wars Story', 'box_office__46': 1057420387.0, 'country__46': None, 'year__46': 2016, 'director__47': 'Guy Ritchie', 'rank__47': 48, 'title__47': 'Aladdin', 'box_office__47': 1050693953.0, 'country__47': 'United States', 'year__47': 2019, 'director__48': 'George Lucas', 'rank__48': 49, 'title__48': 'Star Wars: Episode I – The Phantom Menace', 'box_office__48': 1046515409.0, 'country__48': 'United States', 'year__48': 1999, 'director__49': 'Rob Marshall', 'rank__49': 50, 'title__49': 'Pirates of the Caribbean: On Stranger Tides', 'box_office__49': 1045713802.0, 'country__49': 'United States', 'year__49': 2011}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

## 5. Export to JSON (for GitHub Pages)

In [92]:
df_clean.to_json('films.json', orient='records', force_ascii=False, indent=2)
print('Exported → films.json')

with open('films.json') as f:
    data = json.load(f)
print(json.dumps(data[0], indent=2, ensure_ascii=False))

Exported → films.json
{
  "rank": 1,
  "title": "Avatar",
  "year": 2009,
  "director": "James Cameron",
  "box_office": 2923710708.0,
  "country": "United States, United Kingdom"
}